# Все интервалы и первое появление в минутах. Москва (UTC+3).
BOSSES = [
    {"name": "Андрас", "chance": 50, "first_spawn_minutes": 600, "respawn_minutes": 720},
    {"name": "Базил", "chance": 50, "first_spawn_minutes": None, "respawn_minutes": 150},
    {"name": "Баллак", "chance": 50, "first_spawn_minutes": 360, "respawn_minutes": 1440},
    {"name": "Бальбо", "chance": 50, "first_spawn_minutes": 360, "respawn_minutes": 480},
    {"name": "Барон", "chance": 33, "first_spawn_minutes": 840, "respawn_minutes": 1440},
    {"name": "Брека", "chance": 50, "first_spawn_minutes": None, "respawn_minutes": 240},
    {"name": "Буря", "chance": 50, "first_spawn_minutes": None, "respawn_minutes": 210},
    {"name": "Гарет", "chance": 50, "first_spawn_minutes": 360, "respawn_minutes": 360},
    {"name": "Гекатон", "chance": 50, "first_spawn_minutes": None, "respawn_minutes": 360},
    {"name": "Глаки", "chance": 100, "first_spawn_minutes": 840, "respawn_minutes": 480},
    {"name": "Зараженный Крума", "chance": 100, "first_spawn_minutes": 360, "respawn_minutes": 480},
    {"name": "Зеркало Забвения", "chance": 100, "first_spawn_minutes": 600, "respawn_minutes": 720},
    {"name": "Кабрио", "chance": 50, "first_spawn_minutes": 600, "respawn_minutes": 720},
    {"name": "Каменук", "chance": 100, "first_spawn_minutes": None, "respawn_minutes": 240},
    {"name": "Катан", "chance": 100, "first_spawn_minutes": 360, "respawn_minutes": 480},
    {"name": "Кельсус", "chance": 50, "first_spawn_minutes": 360, "respawn_minutes": 360},
    {"name": "Королева Муравьев", "chance": 33, "first_spawn_minutes": 840, "respawn_minutes": 360},
    {"name": "Корун", "chance": 100, "first_spawn_minutes": 360, "respawn_minutes": 600},
    {"name": "Ландор", "chance": 100, "first_spawn_minutes": 600, "respawn_minutes": 480},
    {"name": "Матура", "chance": 50, "first_spawn_minutes": None, "respawn_minutes": 240},
    {"name": "Медуза", "chance": 100, "first_spawn_minutes": None, "respawn_minutes": 420},
    {"name": "Модеус", "chance": 33, "first_spawn_minutes": 840, "respawn_minutes": 1440},
    {"name": "Мутант Крума", "chance": 100, "first_spawn_minutes": 360, "respawn_minutes": 480},
    {"name": "Наяда", "chance": 50, "first_spawn_minutes": 600, "respawn_minutes": 720},
    {"name": "Олкут", "chance": 33, "first_spawn_minutes": 840, "respawn_minutes": 1440},
    {"name": "Орфен", "chance": 33, "first_spawn_minutes": 840, "respawn_minutes": 1440},
    {"name": "Пан Драйд", "chance": 100, "first_spawn_minutes": None, "respawn_minutes": 480},
    {"name": "Пан Марод", "chance": 50, "first_spawn_minutes": None, "respawn_minutes": 180},
    {"name": "Рахха", "chance": 33, "first_spawn_minutes": 840, "respawn_minutes": 1980},
    {"name": "Репиро", "chance": 50, "first_spawn_minutes": None, "respawn_minutes": 300},
    {"name": "Сабан", "chance": 100, "first_spawn_minutes": 360, "respawn_minutes": 720},
    {"name": "Сайракс", "chance": 50, "first_spawn_minutes": 360, "respawn_minutes": 1440},
    {"name": "Самуэль", "chance": 100, "first_spawn_minutes": 600, "respawn_minutes": 720},
    {"name": "Селу", "chance": 50, "first_spawn_minutes": None, "respawn_minutes": 450},
    {"name": "Сусцептор Ядра", "chance": 33, "first_spawn_minutes": 840, "respawn_minutes": 720},
    {"name": "Талакин", "chance": 100, "first_spawn_minutes": None, "respawn_minutes": 420},
    {"name": "Талкин", "chance": 50, "first_spawn_minutes": None, "respawn_minutes": 300},
    {"name": "Танатос", "chance": 50, "first_spawn_minutes": 840, "respawn_minutes": 1440},
    {"name": "Тиминиэль", "chance": 100, "first_spawn_minutes": 360, "respawn_minutes": 480},
    {"name": "Тимитрис", "chance": 100, "first_spawn_minutes": None, "respawn_minutes": 300},
    {"name": "Фаробос", "chance": 50, "first_spawn_minutes": None, "respawn_minutes": 270},
    {"name": "Фелис", "chance": 50, "first_spawn_minutes": None, "respawn_minutes": 120},
    {"name": "Феникс", "chance": 50, "first_spawn_minutes": 840, "respawn_minutes": 1440},
    {"name": "Фоллинт", "chance": 50, "first_spawn_minutes": 600, "respawn_minutes": 480},
    {"name": "Хафф", "chance": 50, "first_spawn_minutes": 600, "respawn_minutes": 1440},
    {"name": "Хисилром", "chance": 50, "first_spawn_minutes": 360, "respawn_minutes": 360},
    {"name": "Черная Лилия", "chance": 100, "first_spawn_minutes": 600, "respawn_minutes": 720},
    {"name": "Чертуба", "chance": 50, "first_spawn_minutes": None, "respawn_minutes": 180},
    {"name": "Чудовище", "chance": 100, "first_spawn_minutes": 360, "respawn_minutes": 360},
    {"name": "Чудовищный Дракон", "chance": 33, "first_spawn_minutes": 840, "respawn_minutes": 720},
    {"name": "Шарка", "chance": 100, "first_spawn_minutes": None, "respawn_minutes": 420},
    {"name": "Энкура", "chance": 50, "first_spawn_minutes": None, "respawn_minutes": 210},
]
